# Generated by Django 4.2.8 on 2024-01-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0003_remove_shop_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
