# Generated by Django 4.2.8 on 2024-01-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcp', '0005_alter_price_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product_url',
            field=models.URLField(max_length=750),
        ),
    ]
